language: python

sudo: true

env:
    global:
        - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/matchzoo

matrix:
    include:
        - os: linux
          dist: trusty
          python: 3.6
        - os: osx
          language: generic
          env: PYTHON_VERSION=3.6

install:
  - pip3 install -r requirements.txt
  - python3 -m nltk.downloader punkt
  - python3 -m nltk.downloader wordnet
  - python3 -m nltk.downloader stopwords

script:
  - stty cols 80
  - export COLUMNS=80
  - make test

after_success:
      - codecov