language: python
virtualenv:
  system_site_packages: true
matrix:
    include:
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: osx
          sudo: enabled
          language: generic
          python: 3.6
          env: TOXENV=py36
install:
  - "pip install -r requirements.txt"
  - "python -m nltk.downloader punkt"
  - "python -m nltk.downloader wordnet"
  - "python -m nltk.downloader stopwords"
script: make test
env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/matchzoo
after_success:
      - codecov